apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: profanity-secrets
  namespace: profanity-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: SecretStore
  target:
    name: profanity-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret-source
  - extract:
      key: database-source
