apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: profanity-production

resources:
  - resources.yaml
  - deployment.yaml
  - external-secret.yaml

images:
  - name: docker-registry.bottle-note.com/profanity-api
    newTag: v0.0.1
