apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: profanity-production

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-store.yaml
  - external-secret.yaml
