apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-store
  namespace: profanity-production
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets-system.svc.cluster.local:8080
      vaults:
        profanity: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            key: token
